-- PostgreSQL + PostGIS Initialization Script
-- Derived from the ICS Project II Proposal ERD and Database Schema

-- Enable PostGIS extension for spatial queries
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_raster;

-- 1. SCENES TABLE
-- Stores metadata for Sentinel-1 scenes downloaded from CDSE API
CREATE TABLE IF NOT EXISTS scenes (
    scene_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    acquisition_date TIMESTAMPTZ NOT NULL,
    orbit_direction VARCHAR(20),
    polarisations TEXT[],
    scene_extent GEOGRAPHY(POLYGON, 4326),
    ingested_at TIMESTAMPTZ DEFAULT NOW()
);

-- Spatial index on scene geometries for fast bounds querying
CREATE INDEX idx_scenes_extent ON scenes USING GIST (scene_extent);

-- 2. FLOOD MASKS TABLE
-- Stores the final binary flood masks generated by the U-Net pipeline
CREATE TABLE IF NOT EXISTS flood_masks (
    mask_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scene_id UUID REFERENCES scenes(scene_id) ON DELETE CASCADE,
    model_version VARCHAR(50),
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    flood_raster RASTER,
    classification_thr FLOAT DEFAULT 0.5
);

-- 3. UPLOADED IMAGES TABLE
-- Stores metadata for drone/survey imagery uploaded via the Admin Dashboard
CREATE TYPE processing_status_enum AS ENUM ('pending', 'processing', 'complete', 'failed');

CREATE TABLE IF NOT EXISTS uploaded_images (
    image_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scene_id UUID REFERENCES scenes(scene_id) ON DELETE SET NULL,
    upload_timestamp TIMESTAMPTZ DEFAULT NOW(),
    file_path TEXT NOT NULL,
    processing_status processing_status_enum DEFAULT 'pending',
    source_description TEXT
);

-- Analytics Views
CREATE OR REPLACE VIEW v_flood_impact_analytics AS
SELECT 
    s.acquisition_date,
    SUM(ST_Area(ST_DumpAsPolygons(m.flood_raster)::geometry)) / 1000000.0 AS inundated_area_sqkm,
    m.model_version
FROM flood_masks m
JOIN scenes s ON m.scene_id = s.scene_id
GROUP BY s.acquisition_date, m.model_version
ORDER BY s.acquisition_date ASC;
